set -e
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-hammer /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/corrected/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/corrected/corrected.yaml --ext_python_modules_home /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades --max_threads 8 --output_dir /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/corrected --gzip_output
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K21/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K33/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/before_rr.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/before_rr.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/final_contigs.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/contigs.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/strain_graph.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/strain_graph.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/scaffolds.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/scaffolds.fasta /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/scaffolds.paths /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/scaffolds.paths /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/K55/final_contigs.paths /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/contigs.paths
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/scaffolds.fasta --misc_dir /Users/weeblesthe2nd/Desktop/kosovo_mtb/trimmed_reads/kosovo_spades/misc --threshold_for_breaking_scaffolds 3
true
